#ifndef _INTERFACE_H_
#define _INTERFACE_H_

#ifdef _GS
#define INTERFACE_FUNC_FILLRECT				0x0AFFB20C
#define INTERFACE_FUNC_SETBKMODE			0x0AFFAC04
#define INTERFACE_FUNC_SETTEXTCOLOR			0x0AFFABF0
#define INTERFACE_FUNC_CREATESOLIDBRUSH		0x0AFFABF4
#define INTERFACE_FUNC_SIZEOF				0x00617B30
#define INTERFACE_FUNC_TEXTOUTA				0x0AFFAC6C
#define INTERFACE_FUNC_GITEMLOOP			0x07A4E60

#else
#define INTERFACE_FUNC_FILLRECT				0x073BC20C
#define INTERFACE_FUNC_SETBKMODE			0x073BBC04
#define INTERFACE_FUNC_SETTEXTCOLOR			0x073BBBF0
#define INTERFACE_FUNC_CREATESOLIDBRUSH		0x073BBBF4
#define INTERFACE_FUNC_SIZEOF				0x0064D0F0
#define INTERFACE_FUNC_TEXTOUTA				0x073BBC6C
#define INTERFACE_FUNC_GITEMLOOP			0x07FDBC0
#endif

void InterfaceLoad();

#endif